sudo: required
services:
  - docker
  - mongodb
language: node_js
node_js: 6
script:
  - npm test
  - docker build -t scwood/day-by-day .
  - docker login -u=$DOCKER_HUB_USERNAME -p=$DOCKER_HUB_PASSWORD
  - docker push scwood/day-by-day
after_success:
  - curl -X POST http://deploy.spncrwd.com/day-by-day
