sudo: required
services:
  - docker
  - mongodb
language: node_js
node_js: 6
env:
  global:
    - SECRET=testsecret
    - MONGO_HOST=localhost
    - EMAIL_ADDRESS=noreply.daybyday@gmail.com
    - EMAIL_HOST=smtp.gmail.com  
script:
  - npm test
  # - docker build -t scwood/day-by-day .
  # - docker run --name day-by-day scwood/day-by-day
  # - docker ps | grep -q day-by-day
after_success:
  - docker login -u=$DOCKER_HUB_USERNAME -p=$DOCKER_HUB_PASSWORD
  - docker push scwood/day-by-day
  - curl -X POST http://deploy.spncrwd.com/day-by-day
