sudo: required
services:
  - docker
  - mongodb
language: node_js
node_js: 6
env:
  global:
    - MONGO_HOST=localhost
    - EMAIL_ADDRESS=noreply.daybyday@gmail.com
    - EMAIL_HOST=smtp.gmail.com  
script:
  # - npm test
  # - docker build -t scwood/day-by-day .
  # - docker 
  - docker ps | grep -q day-by-day
